### PR TITLE
Add Linear depth for nativeEngine in v3.1

### PR DESCRIPTION
**Pull request by troublemaker52025**

### CODE REVIEW

**Comment by minggo** [comment]
Please fix coding style issue first.

**Comment by minggo** [comment]
Please fix conflict.

**Review by caryliu1999 — APPROVED** [review]

**Comment by troublemaker52025** [comment]
https://github.com/cocos-creator/engine/pull/8397

**Comment by troublemaker52025** [comment]
https://github.com/cocos-creator/3d-tasks/issues/6785

**Pull request merged**
