### PR TITLE
[Modify] change the combineSigny initialization location

### PR DESCRIPTION
**Pull request by GengineJS**

### CODE REVIEW

**Comment by GengineJS** [comment]
https://github.com/cocos-creator/engine/pull/8406

**Comment by minggo** [comment]
Why need to change it like this?

**Comment by GengineJS** [comment]
> Why need to change it like this?

Mainly in the js engine, the initialize function may not be executed after running. In order to be unified with jsEngine

**Comment by minggo** [comment]
> the initialize function may not be executed after running

@caryliu1999 i think we should fix it. Initialize should be invoked before being used.

**Comment by GengineJS** [comment]
> > the initialize function may not be executed after running
> 
> @caryliu1999 i think we should fix it. Initialize should be invoked before being used.

But to get combineSignY, the device needs to be defined, and the device is assigned in the active function.

**Comment by minggo** [comment]
> But to get combineSignY, the device needs to be defined, and the device is assigned in the active function.

Yep. active() is invoked before initialize(), so device is assigned when invoke initialize().

**Pull request merged**
