### PR TITLE
avoid video play fail when file in /data/ sub path.

### PR DESCRIPTION
**Pull request by xianyinchen**
https://forum.cocos.org/t/topic/124507/20

### CODE REVIEW

**Comment by BrokenTooth1989** [comment]
123

**Comment by minggo** [comment]
This PR seems to include other commits. Could you please fix it?

**Comment by xianyinchen** [comment]
fixed!

**Review by timlyeee — APPROVED** [review]

**Comment by minggo** [comment]
@xianyinchen could you please sync to v3?

**Pull request merged**
