### PR TITLE
V3.6 merge v3.5.0

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by YunHsiao** [comment]
@minggo #4169 was merged yesterday, need to sync again

**Comment by minggo** [comment]
Does engine includes it too? If not, then i will sync it in another PR as this PR if very complex now, and have many conflicts.

**Comment by YunHsiao** [comment]
Yes, both repos need to be synced

**Comment by minggo** [comment]
I think we can sync it later.

**Comment by minggo** [comment]
合并分支不处理 clang-tidy 问题。

**Pull request merged**
