### PR TITLE
ios compiling error & mac full screen

### PR DESCRIPTION
**Pull request by hana-alice**
https://github.com/cocos-creator/3d-tasks/issues/7212

https://github.com/cocos-creator/3d-tasks/issues/7242

### CODE REVIEW

**Review by minggo — APPROVED** [review]

**Comment by minggo** [comment]
Which modification will fix iOS compiling error?

**Comment by hana-alice** [comment]
> Which modification will fix iOS compiling error?

"platform/device.h" -> upper case "platform/Device.h"
on some macbook, maybe a result of old-version xcode.

**Comment by minggo** [comment]
Yep, and i think it is fixed in another PR.

**Comment by minggo** [comment]
Oh, you closed that PR. I think it is better to fix iOS compiling error in a separate PR as it is more important than mac full screen issue.

**Pull request closed without merging**
